# 注意保存为UTF-8格式
spring:
  profiles:
    active:
    - dev

---

server:
  port: 8201
spring:
  profiles: dev
  application:
    name: dahe-data-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://dahe7001.com:7001/eureka/,http://dahe7002.com:7002/eureka/,http://dahe7003.com:7003/eureka/
  instance:
      instance-id: config-8201  #页面上显示别名
      prefer-ip-address: true   #访问路径可以显示IP地址

---

server:
  port: 8202
spring:
  profiles: test
  application:
    name: dahe-data-config-test
eureka:
  client:
    service-url:
      defaultZone: http://dahe7001.com:7001/eureka/,http://dahe7002.com:7002/eureka/,http://dahe7003.com:7003/eureka/
  instance:
      instance-id: config-8202  #页面上显示别名
      prefer-ip-address: true   #访问路径可以显示IP地址