# 注意保存为UTF-8格式
spring:
  profiles:
    active:
    - dev

---

server:
  port: 8201
spring:
  profiles: dev
  application:
    name: dahe-data-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://dahe-dev7001.com:7001/eureka/

---

server:
  port: 8202
spring:
  profiles: test
  application:
    name: dahe-data-config-test
eureka:
  client:
    service-url:
      defaultZone: http://dahe-test7001.com:7001/eureka/